import { defineHook } from '@directus/extensions-sdk'
import { sendTemplatedEmail, type EmailServiceContext } from '../shared/email-service.ts'
import { createHookErrorConstructor } from '../shared/errors.ts'
import { postSlackMessage } from '../shared/postSlackMessage.ts'
import { safeAction } from '../shared/safeHook.ts'
import { getRequiredSetting } from '../shared/settings.ts'

const HOOK_NAME = 'newsletter-double-opt-in'
const COLLECTION = 'newsletter_subscribers'

// The confirmation link is valid for 24 hours. `confirm_token_expires_at` is
// NOT NULL and has no database default, so the filter below MUST populate it —
// otherwise every real signup would fail the insert.
const CONFIRM_TOKEN_TTL_MS = 24 * 60 * 60 * 1000

const TEMPLATE_KEY = 'newsletter_double_opt_in'

/**
 * Double-opt-in flow for newsletter subscribers.
 *
 * The website writes only `{ email }`. Directus fills the technical fields:
 * `confirm_token` / `unsubscribe_token` (uuid special flags), `signed_up_at`
 * (date-created) and `status` (default 'pending'). The one field it cannot
 * derive on its own is `confirm_token_expires_at` — this hook sets it, then
 * sends the confirmation mail once the row exists.
 */
export default defineHook(({ filter, action }, hookContext) => {
    const logger = hookContext.logger
    const services = hookContext.services
    const getSchema = hookContext.getSchema

    if (!services.MailService) {
        logger.warn(`${HOOK_NAME}: MailService not available. The double-opt-in email will not be sent.`)
        logger.warn(`${HOOK_NAME}: Make sure Directus email is configured in .env (EMAIL_TRANSPORT, etc.)`)
    }

    /**
     * BEFORE the row is written: stamp the confirmation window. A `filter`
     * (not `action`) is required because the column is NOT NULL with no default.
     */
    filter(`${COLLECTION}.items.create`, (payload: any) => {
        try {
            // Respect an explicitly supplied value (e.g. a data import); only
            // default when the caller — like the website — omitted it.
            if (payload && payload.confirm_token_expires_at) {
                return payload
            }

            const expiresAt = new Date(Date.now() + CONFIRM_TOKEN_TTL_MS).toISOString()
            return { ...(payload ?? {}), confirm_token_expires_at: expiresAt }
        } catch (error: any) {
            logger.error(`${HOOK_NAME} hook: filter error: ${error.message}`)
            const hookError = createHookErrorConstructor(HOOK_NAME, error.message)
            throw new hookError()
        }
    })

    /**
     * AFTER the row exists: send the double-opt-in confirmation mail. The
     * `confirm_token` is generated by Directus during the insert, so we read the
     * persisted item back to obtain it.
     */
    action(
        `${COLLECTION}.items.create`,
        safeAction(HOOK_NAME, logger, async (metadata: any, eventContext: any) => {
            const key = metadata?.key
            if (key === undefined || key === null) {
                logger.warn(`${HOOK_NAME}: create action fired without a key; skipping`)
                return
            }

            const context: EmailServiceContext = {
                logger,
                services,
                getSchema,
                accountability: eventContext?.accountability,
            }

            const schema = await getSchema()
            const subscribersService = new services.ItemsService(COLLECTION, {
                schema,
                accountability: { admin: true },
            })

            const subscriber = await subscribersService.readOne(key, {
                fields: ['id', 'email', 'status', 'confirm_token'],
            })

            if (!subscriber) {
                logger.error(`${HOOK_NAME}: subscriber ${key} not found after create`)
                return
            }

            // Only pending subscribers get a confirmation mail. Guards against
            // re-fires and against rows imported directly in a confirmed state.
            if (subscriber.status !== 'pending') {
                logger.info(
                    `${HOOK_NAME}: subscriber ${key} created as '${subscriber.status}', no confirmation mail sent`
                )
                return
            }

            // Whenever the confirmation mail cannot be sent, the subscriber is
            // stuck in 'pending' with no way to confirm. Logs alone live only in
            // the hosting dashboard, so alert a human via Slack.
            const notifyFailure = async (reason: string) => {
                const message =
                    `:warning: *Newsletter*: Double-Opt-in-Mail an ${subscriber.email} nicht gesendet ` +
                    `(${reason}). Der Subscriber bleibt 'pending'.`
                try {
                    await postSlackMessage(message)
                } catch (slackError: any) {
                    logger.error(`${HOOK_NAME}: Slack notification failed: ${slackError?.message ?? slackError}`)
                }
            }

            // `website_url` is baked into the confirmation link inside a mail we
            // then send — a wrong or guessed host silently breaks confirmation.
            // Require it explicitly rather than falling back to a default.
            let websiteUrl: string
            try {
                websiteUrl = await getRequiredSetting('website_url', context)
            } catch {
                await notifyFailure("Setting 'website_url' ist nicht konfiguriert")
                return
            }

            const confirmUrl = `${websiteUrl}/newsletter/confirm?token=${encodeURIComponent(subscriber.confirm_token)}`

            const sent = await sendTemplatedEmail(
                {
                    templateKey: TEMPLATE_KEY,
                    to: subscriber.email,
                    data: { confirm_url: confirmUrl },
                },
                context
            )

            if (!sent) {
                await notifyFailure(`Template '${TEMPLATE_KEY}' fehlt oder der Mailversand schlug fehl`)
                return
            }

            logger.info(`${HOOK_NAME}: sent double-opt-in mail to ${subscriber.email}`)
        })
    )

    logger.info(`${HOOK_NAME} hook registered`)
})
