// @ts-check
import { existsSync } from 'node:fs'
import prettier from 'eslint-config-prettier'

const GENERATED_CONFIG = './.nuxt/eslint.config.mjs'

/**
 * ESLint flat config. Replaces `.eslintrc.js`, which extended `@nuxt/eslint-config@0.2`,
 * `plugin:nuxt/recommended` (from the unmaintained `eslint-plugin-nuxt`) and `prettier`.
 *
 * The base config is generated by the `@nuxt/eslint` module into `.nuxt/eslint.config.mjs` from
 * `nuxt.config.ts`, so it already knows this app's directory layout, auto-imported globals and
 * generated files. That means **`nuxt prepare` must have run before linting** — it does, via the
 * `postinstall` script, which `npm ci` triggers in CI.
 *
 * Imported dynamically only so that the "you haven't generated it yet" case — a fresh clone, a
 * deleted `.nuxt`, `npm ci --ignore-scripts` — reports something actionable instead of a bare
 * `ERR_MODULE_NOT_FOUND`. The scaffolded config from `@nuxt/eslint` uses a static import; this is
 * the one deliberate deviation from it.
 */
const { default: withNuxt } = await import(GENERATED_CONFIG).catch((error) => {
    // Translate ONLY "the generated file itself is absent". Anything else — a syntax error inside
    // the generated config, or a module *it* imports being missing — has to surface as itself; a
    // handler that blames `nuxt prepare` for unrelated breakage is worse than the raw error it
    // replaces.
    //
    // Decided on the filesystem rather than by matching the error message. Node phrases this as
    // `Cannot find module 'X' imported from Y`, so a missing *transitive* import still names this
    // file as Y — a message check keys off the importer and mistakes a broken dependency for a
    // missing config. Verified: that exact case was misreported before this was changed.
    if (existsSync(new URL(GENERATED_CONFIG, import.meta.url))) throw error

    throw new Error(
        `ESLint cannot run: ${GENERATED_CONFIG} has not been generated.\n` +
            `It is written by the @nuxt/eslint module, so run \`npm run postinstall\` (nuxt prepare) first.\n` +
            `A plain \`npm install\`/\`npm ci\` does this automatically unless scripts are skipped.`
    )
})
export default withNuxt(
    {
        name: 'programmierbar/vue',
        rules: {
            // Carried over from .eslintrc.js: pages and the error page are legitimately
            // single-word here (`index.vue`, `error.vue`, `login.vue`).
            'vue/multi-word-component-names': 'off',
        },
    },
    {
        // Scoped, unlike the flat rule in .eslintrc.js. This rule calls `getParserServices`, so it
        // only runs under `@typescript-eslint/parser`; applied globally it hard-errors on any file
        // espree parses — including this config file — with the misleading "requires type
        // information" message.
        name: 'programmierbar/typescript',
        files: ['**/*.ts', '**/*.mts', '**/*.cts', '**/*.tsx', '**/*.vue'],
        rules: {
            // Carried over from .eslintrc.js. Worth keeping deliberately rather than by
            // inheritance: this codebase leans on `import type` being erased at runtime — see the
            // two dangling type imports recorded in the follow-up backlog, which survive only
            // because of it.
            '@typescript-eslint/consistent-type-imports': 'error',

            // Both of these are demoted to warnings on purpose, so this config swap stays a
            // tooling change. `@nuxt/eslint-config@1` is far stricter than the `0.2` it replaces,
            // and switching it on as-is turns 118 pre-existing findings into build failures:
            //
            //   no-explicit-any   103  newly enabled — was not in the 0.2 rule set at all
            //   no-unused-vars     15  was already reported, but as a *warning* under 0.2
            //
            // Fixing 103 `any`s is a typing project, not a lint upgrade, and it belongs with the
            // vue-tsc burn-down in the follow-up backlog — same class of problem, same files.
            // Demoting keeps the signal visible while preserving the gate Phase 0 chose
            // deliberately: fail on errors, leave pre-existing warnings ungated rather than block
            // on unrelated cleanup. `no-unused-vars` at 'warn' is literally its previous behaviour.
            //
            // Raise either to 'error' once its count is zero, alongside `--max-warnings 0`.
            '@typescript-eslint/no-explicit-any': 'warn',
            '@typescript-eslint/no-unused-vars': 'warn',
        },
    },
    // Last, so it wins: switches off the stylistic rules that would otherwise argue with Prettier.
    // `.eslintrc.js` extended `'prettier'` for the same reason and in the same position.
    prettier
)
