// @ts-check
import prettier from 'eslint-config-prettier'
import withNuxt from './.nuxt/eslint.config.mjs'

/**
 * ESLint flat config. Replaces `.eslintrc.js`, which extended `@nuxt/eslint-config@0.2`,
 * `plugin:nuxt/recommended` (from the unmaintained `eslint-plugin-nuxt`) and `prettier`.
 *
 * The base config is generated by the `@nuxt/eslint` module into `.nuxt/eslint.config.mjs` from
 * `nuxt.config.ts`, so it already knows this app's directory layout, auto-imported globals and
 * generated files. That means **`nuxt prepare` must have run before linting** — it does, via the
 * `postinstall` script, which `npm ci` triggers in CI.
 */
export default withNuxt(
    {
        name: 'programmierbar/vue',
        rules: {
            // Carried over from .eslintrc.js: pages and the error page are legitimately
            // single-word here (`index.vue`, `error.vue`, `login.vue`).
            'vue/multi-word-component-names': 'off',
        },
    },
    {
        // Scoped, unlike the flat rule in .eslintrc.js. This rule calls `getParserServices`, so it
        // only runs under `@typescript-eslint/parser`; applied globally it hard-errors on any file
        // espree parses — including this config file — with the misleading "requires type
        // information" message.
        name: 'programmierbar/typescript',
        files: ['**/*.ts', '**/*.mts', '**/*.cts', '**/*.tsx', '**/*.vue'],
        rules: {
            // Carried over from .eslintrc.js. Worth keeping deliberately rather than by
            // inheritance: this codebase leans on `import type` being erased at runtime — see the
            // two dangling type imports recorded in the follow-up backlog, which survive only
            // because of it.
            '@typescript-eslint/consistent-type-imports': 'error',

            // Both of these are demoted to warnings on purpose, so this config swap stays a
            // tooling change. `@nuxt/eslint-config@1` is far stricter than the `0.2` it replaces,
            // and switching it on as-is turns 118 pre-existing findings into build failures:
            //
            //   no-explicit-any   103  newly enabled — was not in the 0.2 rule set at all
            //   no-unused-vars     15  was already reported, but as a *warning* under 0.2
            //
            // Fixing 103 `any`s is a typing project, not a lint upgrade, and it belongs with the
            // vue-tsc burn-down in the follow-up backlog — same class of problem, same files.
            // Demoting keeps the signal visible while preserving the gate Phase 0 chose
            // deliberately: fail on errors, leave pre-existing warnings ungated rather than block
            // on unrelated cleanup. `no-unused-vars` at 'warn' is literally its previous behaviour.
            //
            // Raise either to 'error' once its count is zero, alongside `--max-warnings 0`.
            '@typescript-eslint/no-explicit-any': 'warn',
            '@typescript-eslint/no-unused-vars': 'warn',
        },
    },
    // Last, so it wins: switches off the stylistic rules that would otherwise argue with Prettier.
    // `.eslintrc.js` extended `'prettier'` for the same reason and in the same position.
    prettier
)
