// @ts-check
import { existsSync } from 'node:fs'
import prettier from 'eslint-config-prettier'

const GENERATED_CONFIG = './.nuxt/eslint.config.mjs'

/**
 * The base config is generated by the `@nuxt/eslint` module from `nuxt.config.ts`, so it already
 * knows this app's directory layout, auto-imported globals and generated files. That means
 * **`nuxt prepare` must have run before linting** — it does, via `postinstall`.
 *
 * Imported dynamically, unlike the config `@nuxt/eslint` scaffolds, so that a missing generated
 * file reports something actionable instead of a bare `ERR_MODULE_NOT_FOUND`.
 */
const { default: withNuxt } = await import(GENERATED_CONFIG).catch((error) => {
    // Test the filesystem, not the error message: Node phrases a missing module as `Cannot find
    // module 'X' imported from Y`, so a broken *transitive* import still names this file as Y and a
    // message check would misreport it as "nuxt prepare was not run".
    if (existsSync(new URL(GENERATED_CONFIG, import.meta.url))) throw error

    throw new Error(
        `ESLint cannot run: ${GENERATED_CONFIG} has not been generated.\n` +
            `It is written by the @nuxt/eslint module, so run \`npm run postinstall\` (nuxt prepare) first.\n` +
            `A plain \`npm install\`/\`npm ci\` does this automatically unless scripts are skipped.`
    )
})
export default withNuxt(
    {
        name: 'programmierbar/vue',
        rules: {
            // Pages and the error page are legitimately single-word (`index.vue`, `error.vue`).
            'vue/multi-word-component-names': 'off',
        },
    },
    {
        // Keep this block scoped by `files`. Its rules call `getParserServices`, so they only run
        // under `@typescript-eslint/parser`; applied globally they hard-error on every file espree
        // parses — including this one — with a misleading "requires type information" message.
        name: 'programmierbar/typescript',
        files: ['**/*.ts', '**/*.mts', '**/*.cts', '**/*.tsx', '**/*.vue'],
        rules: {
            // This codebase relies on `import type` being erased at runtime.
            '@typescript-eslint/consistent-type-imports': 'error',

            // Warnings, not errors, because both have a pre-existing backlog that belongs with the
            // vue-tsc burn-down rather than with lint config. Raise either to 'error' once its
            // count reaches zero, alongside `--max-warnings 0`.
            '@typescript-eslint/no-explicit-any': 'warn',
            '@typescript-eslint/no-unused-vars': 'warn',
        },
    },
    // Last, so it wins: switches off the stylistic rules that would otherwise argue with Prettier.
    prettier
)
