name: Run tests

on:
  pull_request:
    paths:
      - 'directus-cms/extensions/directus-extension-programmierbar-bundle/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: directus-cms/extensions/directus-extension-programmierbar-bundle
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test